### PR TITLE
Snippet added: configure default site creation, and provide better default domain (localhost:8000)

### PR DESCRIPTION
**Pull request by chrischambers**
See description at: http://djangosnippets.org/snippets/2536/

### CODE REVIEW

**Comment by shaunsephton** [comment]
Thanks for this Chris. Can you maybe add some docs to README.rst and I'll merge? I normally just mangle the snippet's description. Thanks again.

**Comment by chrischambers** [comment]
Added documentation, as requested. :)

**Comment by shaunsephton** [comment]
Merged. I've added a requirement to specify a CREATE_DEFAULT_SITE = True setting, just to make it explicit. Also slightly reworded your docs. Thanks for the contribution.

**Comment by shaunsephton** [comment]
Included as part of [v0.0.7](http://pypi.python.org/pypi/django-snippetscream), thanks again for the contribution.

**Pull request merged**
