### PR TITLE
Removed monkey-patching

### PR DESCRIPTION
**Pull request by aehlke**

### CODE REVIEW

**Comment by aehlke** [comment]
Hey sorry for the lack of description, but would you mind taking a look at this? The monkeypatching this snippet had was unnecessary, and there was a bug in it that I fixed as well. Thanks!

**Comment by shaunsephton** [comment]
Sorry for the delay :)

**Comment by shaunsephton** [comment]
Included as part of [v0.0.7](http://pypi.python.org/pypi/django-snippetscream), thanks for the contribution.

**Comment by aehlke** [comment]
thanks!

**Pull request merged**
